enyo.depends(
  "source/biblezPopup.js",
  "source/app.js",
  "source/api.js",
  "source/mainView.js",
  "source/verseView.js",
  "source/widget.js",
  "source/popup.js",
  "source/stuff.js",
  "source/biblezModuleManager.js",
  "source/biblezPrefs.js",
  "source/mapping.js",
  "css/biblez.css"
);
